export const ADD_TO_CART = "addToCart"
export const REMOVE_FROM_CART = "removeFromCart"
export const CART_RESET = "cartReset"
export const GET_CART_SUCCESS = "getCartSuccess"
export const GET_CART_FAILURE = "getCartFailure"